name: Dependency & Lint Check

on:
  pull_request:
    branches: [ '*' ]

jobs:
  requirementsCheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Check for vulnerable dependencies
      run: |
        safety check --full-report
  
  lintCheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    
    - name: Lint Check with Flake8
      run: |
        flake8 --ignore=W191,E265,E101,E126,F401,E122,F841,W504,E302,E117,E712,W291,F541,E275,E251,E501,E203,E303,W292,E305,E123,E402,E231,E266,E225,W293 scripts/